### PR TITLE
feat: replace minimatch with micromatch

### PR DESCRIPTION
**Pull request by curbengh**
I previously detailed the benefits of micromatch in https://github.com/hexojs/hexo/pull/3538
TL;DR micromatch is more active and support more [globbing patterns](https://github.com/micromatch/picomatch#library-comparisons).

### CODE REVIEW

**Comment by ertrzyiks** [comment]
No objections from my side. Will test later soon. Do you mind updating README as well? It still links to minimatch:

> A minimatch pattern. All matching assets will use the assigned size rules.

**Comment by curbengh** [comment]
Updated readme.

btw, I just noticed the readme includes `squares/*.jpg` pattern. This pattern doesn't work with micromatch nor minimatch.

``` js
const micromatch = require('micromatch')
console.log(micromatch.isMatch('/jack/hey/foo/bar.img', 'foo/*.img'))
// false

const minimatch = require('minimatch')
console.log(minimatch('/jack/hey/foo/bar.img', 'foo/*.img'))
// false
```

**Comment by ertrzyiks** [comment]
@curbengh case of `'/jack/hey/foo/bar.img`is not a big deal since the filter is applied to URLs, not file system path. 

Thanks for the contribution, it works nicely on my machine!

**Comment by ertrzyiks** [comment]
Released as 1.4.3

**Comment by curbengh** [comment]
> case of `/jack/hey/foo/bar.img`is not a big deal since the filter is applied to URLs, not file system path.

But it doesn't match `http://example.com/baz/foo/baz.img` too.

``` js
console.log(micromatch.isMatch('http://example.com/baz/foo/baz.img', 'foo/*.img'))
// false

console.log(micromatch.isMatch('http://example.com/baz/foo/baz.img', '**/foo/*.img'))
// true
```

I'm not very familiar with this plugin, perhaps I missed something?

**Comment by ertrzyiks** [comment]
My point is that if the images are hosted under `foo` folder like http://example.com/foo/baz.img
then this is totally correct configuration
```
foo/*.img
```

because what will happen in this plugin is that
```
console.log(micromatch.isMatch('foo/baz.img', 'foo/*.img'))
```

If you need nested lookup to match `baz/foo/avatar.img` then you need something like `**/foo/*.img` indeed.

**Pull request merged**
